#!/bin/sh
#
#  try ftp 5 times in 120 seconds interval if not connected
#
# $1 is ftp description data
# $2 is ftp output
# $3 is address of ftp site
# $4 is ftp protocol (ftp, sftp,....)
#
if [ $# -ne 4 ] ; then
	echo wrong ftpscr argument
	exit 8
fi
#
ftpdata=$1
ftpout=$2
address=$3
protocol=$4
#
if [ -z "$protocol" ] ; then
	protocol=ftp
fi
if [ $protocol = hsi ] ; then
	address=
fi
#
waittime=120
count=1
dum=
while [ -z "$dum" ] ; do
	$protocol $address <$ftpdata 1>$ftpout 2>&1
	grep 'Not connected' $ftpout  >/dev/null
	if [ $? -eq 0 ] ; then
		if [ $count -gt 5 ] ; then
			echo "$protocol not connected"
			echo "`date` $0: $protocol not connected for $ftpdata $ftpout $address." >>ERROR.out
			exit 8
		else
			sleep $waittime
			count=`expr $count + 1`
		fi
	else
		grep 'No such file or directory' $ftpout >/dev/null
		if [ $? -eq 0 ] ; then
			echo "$protocol to $address faild"
			echo "$protocol input:"
			cat $ftpdata
			echo "$protocol output:"
			cat $ftpout
			exit 8
		else
			echo "$protocol connection to $address successful" >>$ftpout
			break
		fi
	fi
done

