#!/bin/sh
set -ax

YYYYs=`echo $1 | cut -d':' -f1`
MMs=`echo $1 | cut -d':' -f2`
DDs=`echo $1 | cut -d':' -f3`
HHs=`echo $1 | cut -d':' -f4`

cd $Model_WRF_Dir
mpirun -np $wrfNCPU $Model_WRF_Dir/wrf.exe || exit 8

#mv rsl.out.0000 $WRF_Runlog_Dir/out.$YYYYs$MMs$DDs$HHs
#mv rsl.error.0000 $WRF_Runlog_Dir/error.$YYYYs$MMs$DDs$HHs
#mv rsl.out.0000 $WRF_Runlog_Dir/
#mv rsl.error.0000 $WRF_Runlog_Dir/
rm rsl.error.* 2>/dev/null
rm rsl.out.* 2>/dev/null

cd -
